version: "3.9"
services:
  database:
    image: "dbz-character-service-db"
    volumes:
      - "dbz-character-database-volume:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  character_service:
    image: "dbz-character-service"
    network_mode: host
    depends_on:
      - database

volumes:
  dbz-character-database-volume:
    external: true


# J'ai viré network mode et l'ai remplacé par ports
# J'ai changé /var/lib/postgresql/data/postgresql.conf 
# - J'ai changé listen addresses à *
