version: "3.9"
services:
  database:
    image: "dbz-character-service-db"
    volumes:
      - "dbz-character-database-volume:/var/lib/postgresql/data"
    network_mode: host

  character_service:
    image: "dbz-character-service"
    network_mode: host
    depends_on:
      - database

volumes:
  dbz-character-database-volume:
    external: true
